title: <Claudia Weitman> # your name (or website title) here
logo: "IMG_7492.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Undergraduate Student in... environmental economics & geological oceanography
  <br><br>
  College of the Environment and Life Sciences
  <br><br>
  <a href="https://www.linkedin.com/in/claudia-weitman-233820186/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
